"""add trace name

Revision ID: bc7d8bebb9aa
Revises: e3f3704d8454
Create Date: 2026-05-30 21:53:51.114735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc7d8bebb9aa'
down_revision: Union[str, Sequence[str], None] = 'e3f3704d8454'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('traces', sa.Column('trace_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('traces', 'trace_name')
    # ### end Alembic commands ###
